"""empty message

Revision ID: 8e64e934150b
Revises: 28d2447f5bc8
Create Date: 2024-01-24 03:24:36.179931

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8e64e934150b"
down_revision = "28d2447f5bc8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "mentor_mentee", ["mentor_id", "mentee_id"])
    op.add_column(
        "profile",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "profile",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("profile", "updated_at")
    op.drop_column("profile", "created_at")
    op.drop_constraint(None, "mentor_mentee", type_="unique")
    # ### end Alembic commands ###
