"""empty message

Revision ID: f152bcd7ff6f
Revises: 9217e7fb1540
Create Date: 2024-02-09 02:26:59.936362

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f152bcd7ff6f"
down_revision = "9217e7fb1540"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comment_reply",
        sa.Column("comment_id", sa.Uuid(), nullable=False),
        sa.Column("reply_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["comment_id"], ["comment.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["reply_id"], ["comment.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("comment_id", "reply_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("comment_reply")
    # ### end Alembic commands ###
