"""empty message

Revision ID: 5fbf1a6784b6
Revises: 8e64e934150b
Create Date: 2024-01-24 03:44:24.440416

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5fbf1a6784b6"
down_revision = "8e64e934150b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("experience_user_id_fkey", "experience", type_="foreignkey")
    op.create_foreign_key(
        None,
        "experience",
        "user",
        ["user_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "mentor_mentee_history_mentee_id_fkey",
        "mentor_mentee_history",
        type_="foreignkey",
    )
    op.drop_constraint(
        "mentor_mentee_history_mentor_id_fkey",
        "mentor_mentee_history",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "mentor_mentee_history",
        "user",
        ["mentee_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "mentor_mentee_history",
        "user",
        ["mentor_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint("profile_user_id_fkey", "profile", type_="foreignkey")
    op.create_foreign_key(
        None,
        "profile",
        "user",
        ["user_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "profile", type_="foreignkey")
    op.create_foreign_key(
        "profile_user_id_fkey", "profile", "user", ["user_id"], ["id"]
    )
    op.drop_constraint(None, "mentor_mentee_history", type_="foreignkey")
    op.drop_constraint(None, "mentor_mentee_history", type_="foreignkey")
    op.create_foreign_key(
        "mentor_mentee_history_mentor_id_fkey",
        "mentor_mentee_history",
        "user",
        ["mentor_id"],
        ["id"],
    )
    op.create_foreign_key(
        "mentor_mentee_history_mentee_id_fkey",
        "mentor_mentee_history",
        "user",
        ["mentee_id"],
        ["id"],
    )
    op.drop_constraint(None, "experience", type_="foreignkey")
    op.create_foreign_key(
        "experience_user_id_fkey", "experience", "user", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
