"""empty message

Revision ID: 9217e7fb1540
Revises: 9c694dd3ce8e
Create Date: 2024-02-09 02:26:30.762228

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9217e7fb1540"
down_revision = "9c694dd3ce8e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
