"""empty message

Revision ID: c4527ab0d79e
Revises: 5fbf1a6784b6
Create Date: 2024-01-24 22:56:09.355540

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c4527ab0d79e"
down_revision = "5fbf1a6784b6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
