"""empty message

Revision ID: 0612f85d74c0
Revises: bc5620ef32a5
Create Date: 2024-02-01 07:44:57.701514

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0612f85d74c0"
down_revision = "bc5620ef32a5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("booking_activity", "created_at")
    op.drop_column("booking_activity", "updated_at")
    op.drop_column("booking_activity", "id")
    op.drop_constraint(
        "time_slot_day_start_time_end_time_key", "time_slot", type_="unique"
    )
    op.create_unique_constraint(
        None, "time_slot", ["user_id", "day", "start_time", "end_time"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "time_slot", type_="unique")
    op.create_unique_constraint(
        "time_slot_day_start_time_end_time_key",
        "time_slot",
        ["day", "start_time", "end_time"],
    )
    op.add_column(
        "booking_activity",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "booking_activity",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "booking_activity",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
