from enum import Enum


class ErrorMessage(str):
    """Error messages"""

    PROFILE_DOES_NOT_EXIST = "PROFILE_DOES_NOT_EXIST"
    PROFILE_ALREADY_EXISTS = "PROFILE_ALREADY_EXISTS"
    EXPERIENCES_NOT_FOUND = "EXPERIENCES_NOT_FOUND"
    EXPERIENCE_NOT_FOUND = "EXPERIENCE_NOT_FOUND"
    EXPERIENCE_DOES_NOT_EXIST = "EXPERIENCE_DOES_NOT_EXIST"
    UNAUTHORIZED = "UNAUTHORIZED"
    USER_NOT_ASSOCIATED_WITH_AN_ACTIVE_PROFILE = (
        "USER_NOT_ASSOCIATED_WITH_AN_ACTIVE_PROFILE"
    )
    NO_VALID_MENTOR_MENTEE_RECORD = "NO_VALID_MENTOR_MENTEE_RECORD"
    MENTOR_NOT_ASSOCIATED_WITH_AN_ACTIVE_PROFILE = (
        "MENTOR_NOT_ASSOCIATED_WITH_AN_ACTIVE_PROFILE"
    )
    USER_HAS_A_MENTOR_ALREADY = "USER_HAS_A_MENTOR_ALREADY"
